---
apiVersion: v1
kind: secret
metadata:
  name: "{{ $.Values.name }}-secretmap"
  namespace: "{{ $.Values.namespace }}"
data:
  # This value has to be manually updated with a base64 encoded string.
  vite_client_secret: "placeholder"
