{{- if not $.Values.secret.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Values.name }}-secret"
  namespace: "{{ $.Values.namespace }}"
type: Opaque
data:
  MONGODB_PASSWORD: "{{ $.Values.unimq.backend.mongodb_password | b64enc }}"
  RABBITMQ_PASSWORD: "{{ $.Values.unimq.backend.rabbitmq_password | b64enc }}"
  EMAIL_SMTP_PASSWORD: "{{ $.Values.unimq.backend.email_smtp_password | b64enc }}"
  OIDC_CLIENT_SECRET: "{{ $.Values.unimq.backend.oidc_client_secret | b64enc }}"
{{- end }}
