ARG GCR_MIRROR=gcr.io/
#
# FROM ${GCR_MIRROR}distroless/nodejs26-debian13
#
# LABEL org.opencontainers.image.source="https://github.com/norskhelsenett/unimq-dashboard"
#
# WORKDIR /app
#
# COPY /web/static/dist ./dist
# COPY /web-src/package.json ./
# COPY /web-src/package-lock.json ./
# COPY /web-src/node_modules ./node_modules
#
# EXPOSE 5176
#
# CMD ["dist/index.js"]

FROM  nginx:1.25-alpine AS nhn-unimq-dashboard

LABEL org.opencontainers.image.source="https://github.com/norskhelsenett/unimq-dashboard"

COPY web/static/dist /usr/share/nginx/html

EXPOSE 80




