ARG GO_VERSION=1.26.4
FROM golang:${GO_VERSION} AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -o nhn-unimq -ldflags '-w -extldflags "-static"' cmd/unimq/main.go

FROM gcr.io/distroless/static AS unimq-backend

WORKDIR /
COPY --chown=1001:2000 --from=build /app/nhn-unimq /bin/nhn-unimq

EXPOSE 8080

ENTRYPOINT ["/bin/nhn-unimq"]
