ARG GCR_MIRROR=gcr.io/

FROM node:22-alpine AS builder
WORKDIR /app
COPY web-src/package.json web-src/package-lock.json ./
RUN npm ci
COPY web-src/ ./
RUN npm run build

FROM nginx:1.25-alpine AS nhn-unimq-dashboard
LABEL org.opencontainers.image.source="https://github.com/norskhelsenett/unimq-dashboard"
COPY --from=builder /web-src/static/dist /usr/share/nginx/html
COPY dockerfiles/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]
