FROM "golang:latest" AS build

WORKDIR /app
COPY . .

RUN go get ./...
RUN go fmt ./...
RUN go vet ./...
RUN go test ./...
RUN CGO_ENABLED=0 go build -o nhn-unimq -ldflags '-w -extldflags "-static"' cmd/unimq/main.go

FROM gcr.io/distroless/static AS unimq-backend

WORKDIR /
COPY --chown=1001:2000 --from=build /app/nhn-unimq /bin/nhn-unimq

EXPOSE 8080

ENTRYPOINT ["/bin/nhn-unimq"]
