server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

     location = /env.js { alias /tmp/env.js; }

    location = /callback {
        root   /usr/share/nginx/html;
        try_files /entries/callback.html =404;
    }

    location = /notifications {
        root   /usr/share/nginx/html;
        try_files /entries/notifications.html =404;
    }

    location = /profile {
        root   /usr/share/nginx/html;
        try_files /entries/profile.html =404;
    }

    location = /notifications/rule {
        root   /usr/share/nginx/html;
        try_files /entries/notification_rule.html =404;
    }

    location = /maintenance {
        root   /usr/share/nginx/html;
        try_files /entries/maintenance.html =404;
    }

    location = /maintenance/edit {
        root   /usr/share/nginx/html;
        try_files /entries/edit_maintenance.html =404;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
