server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    location = /callback {
        root   /usr/share/nginx/html;
        try_files /callback.html =404;
    }

    location = /notifications {
        root   /usr/share/nginx/html;
        try_files /notifications.html =404;
    }

    location = /profile {
        root   /usr/share/nginx/html;
        try_files /profile.html =404;
    }

    location = /notifications/rule {
        root   /usr/share/nginx/html;
        try_files /notification_rule.html =404;
    }

    location = /maintenance {
        root   /usr/share/nginx/html;
        try_files /maintenance.html =404;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
