name: Release unimq-dashboard

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write
  id-token: write
  actions: write

jobs:
  frontend:
    uses: ./.github/workflows/release_frontend.yaml

  backend:
    uses: ./.github/workflows/release_backend.yaml

  notes:
    uses: ./.github/workflows/release_notes.yaml
