name: Release ROR Web

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: norskhelsenett/unimq-dashboard
  APP: unimq-dashboard

jobs:
  build-ror-web-container-image:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Build web
        uses: actions/setup-node@v3
      - run: mv package.json package-backup.json
      - run: npm ci
      - run: npm run build
