name: Test and build unimq-dashboard frontend

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-src
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: web-src/package-lock.json
      - run: npm ci
      - run: npm run build
