name: Test and build unimq-dashboard helm chart

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Helm
        uses: azure/setup-helm@v5

      - name: Lint chart
        run: helm lint ./unimq

      - name: Template chart
        run: helm template unimq ./unimq
