enabled: true
name: unimq-dashboard
namespace: unimq-dashboard
replicaCount: 1

secret:
  existingSecret: ""

image:
  backend:
    repository: ghcr.io/norskhelsenett/unimq-dashboard/backend
    pullPolicy: IfNotPresent
    tag: ""
  frontend:
    repository: ghcr.io/norskhelsenett/unimq-dashboard/frontend
    pullPolicy: IfNotPresent
    tag: ""

service:
  backend:
    port: 8080
  frontend:
    port: 80

# Gateway API (HTTPRoute) settings.
gateway:
  enabled: true
  name: lt-integrasjon
  namespace: lt-integrasjon
  sectionName: unimq-dashboard.example.no
  hostname: unimq-dashboard.example.no
  annotations:
    gatewayapi-operator.vitistack.io/cluster-issuer: dummy
    gatewayapi-operator.vitistack.io/enabled: "true"

resources:
  limits:
    backend:
      cpu: "500m"
      memory: "256Mi"
    frontend:
      cpu: "100m"
      memory: "64Mi"
  requests:
    backend:
      cpu: "50m"
      memory: "64Mi"
    frontend:
      cpu: "20m"
      memory: "16Mi"

unimq:
  backend:
    # API connection settings
    base_url: "0.0.0.0"
    base_port: "8080"

    # Log level settings, valid values: -8 (trace), -4 (debug), 0 (info), 4 (warn), 8 (error)
    log_level: "0"

    # mongodb connection settings
    mongodb_host: "localhost"
    mongodb_port: "27017"
    mongodb_username: "admin"
    mongodb_database: "unimq"

    # Remember to update this with a real value.
    mongodb_password: "password"

    # rabbitmq connection settings
    rabbitmq_host: "http://localhost"
    rabbitmq_port: "15672"
    rabbitmq_username: "guest"
    # Remember to update this with a real value.
    rabbitmq_password: "guest"

    # email/smtp settings, notifications are disabled when smtp_host is empty
    email_smtp_host: ""
    email_smtp_port: "587"
    email_from_address: "unimq@example.com"
    email_smtp_username: ""
    # Remember to update this with a real value.
    email_smtp_password: ""

    # OIDC authentication settings
    oidc_client_id: "unimq-dashboard"
    oidc_client_secret: "placeholder"
    oidc_url: "http://localhost:5556/dex"
    oidc_redirect_url: "http://localhost/api/v1/login/callback"
    oidc_swagger_client_id: "unimq-swagger"

    admin_groups: "group.name1@local,group.name2@local"
